package org.excellentcoder.tutorial.common.dal.dataobject;

import java.util.Date;

public class VoteDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votes.id
     *
     * @mbg.generated
     */
    private Long     id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votes.user_id
     *
     * @mbg.generated
     */
    private Long     userId;

    /** 用户DO */
    private UserDO   user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votes.poll_id
     *
     * @mbg.generated
     */
    private Long     pollId;

    /** 投票DO */
    private PollDO   poll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votes.choice_id
     *
     * @mbg.generated
     */
    private Long     choiceId;

    /** 选项DO */
    private ChoiceDO choice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votes.gmt_create
     *
     * @mbg.generated
     */
    private Date     gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column votes.gmt_modified
     *
     * @mbg.generated
     */
    private Date     gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votes.id
     *
     * @return the value of votes.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votes.id
     *
     * @param id the value for votes.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votes.user_id
     *
     * @return the value of votes.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votes.user_id
     *
     * @param userId the value for votes.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votes.poll_id
     *
     * @return the value of votes.poll_id
     *
     * @mbg.generated
     */
    public Long getPollId() {
        return pollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votes.poll_id
     *
     * @param pollId the value for votes.poll_id
     *
     * @mbg.generated
     */
    public void setPollId(Long pollId) {
        this.pollId = pollId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votes.choice_id
     *
     * @return the value of votes.choice_id
     *
     * @mbg.generated
     */
    public Long getChoiceId() {
        return choiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votes.choice_id
     *
     * @param choiceId the value for votes.choice_id
     *
     * @mbg.generated
     */
    public void setChoiceId(Long choiceId) {
        this.choiceId = choiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votes.gmt_create
     *
     * @return the value of votes.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votes.gmt_create
     *
     * @param gmtCreate the value for votes.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column votes.gmt_modified
     *
     * @return the value of votes.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column votes.gmt_modified
     *
     * @param gmtModified the value for votes.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    public UserDO getUser() {
        return user;
    }

    public void setUser(UserDO user) {
        this.user = user;
    }

    public PollDO getPoll() {
        return poll;
    }

    public void setPoll(PollDO poll) {
        this.poll = poll;
    }

    public ChoiceDO getChoice() {
        return choice;
    }

    public void setChoice(ChoiceDO choice) {
        this.choice = choice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VoteDO other = (VoteDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
               && (this.getUserId() == null ? other.getUserId() == null
                   : this.getUserId().equals(other.getUserId()))
               && (this.getPollId() == null ? other.getPollId() == null
                   : this.getPollId().equals(other.getPollId()))
               && (this.getChoiceId() == null ? other.getChoiceId() == null
                   : this.getChoiceId().equals(other.getChoiceId()))
               && (this.getGmtCreate() == null ? other.getGmtCreate() == null
                   : this.getGmtCreate().equals(other.getGmtCreate()))
               && (this.getGmtModified() == null ? other.getGmtModified() == null
                   : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getPollId() == null) ? 0 : getPollId().hashCode());
        result = prime * result + ((getChoiceId() == null) ? 0 : getChoiceId().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table votes
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", pollId=").append(pollId);
        sb.append(", choiceId=").append(choiceId);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }
}