package org.excellentcoder.tutorial.common.dal.mapper.auto;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.session.RowBounds;
import org.excellentcoder.tutorial.common.dal.dataobject.ChoiceDO;
import org.excellentcoder.tutorial.common.dal.dataobject.ChoiceDOExample;

@Mapper
public interface ChoiceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    long countByExample(ChoiceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int insert(ChoiceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int insertSelective(ChoiceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    List<ChoiceDO> selectByExampleWithRowbounds(ChoiceDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    List<ChoiceDO> selectByExample(ChoiceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    ChoiceDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChoiceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choices
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChoiceDO record);
}