package org.excellentcoder.tutorial.common.dal.mapper.auto;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.session.RowBounds;
import org.excellentcoder.tutorial.common.dal.dataobject.PollDO;
import org.excellentcoder.tutorial.common.dal.dataobject.PollDOExample;

@Mapper
public interface PollDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table polls
     *
     * @mbg.generated
     */
    long countByExample(PollDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table polls
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table polls
     *
     * @mbg.generated
     */
    int insert(PollDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table polls
     *
     * @mbg.generated
     */
    int insertSelective(PollDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table polls
     *
     * @mbg.generated
     */
    List<PollDO> selectByExampleWithRowbounds(PollDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table polls
     *
     * @mbg.generated
     */
    List<PollDO> selectByExample(PollDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table polls
     *
     * @mbg.generated
     */
    PollDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table polls
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PollDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table polls
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PollDO record);
}